added option for generic text input
added changes to add any text file, not just the ones in JSON format,
into ROOT

diff --git a/CreateLocalCOOLdb b/CreateLocalCOOLdb
--- a/CreateLocalCOOLdb
+++ b/CreateLocalCOOLdb
@@ -19,7 +19,7 @@ OUT_LOG=/dev/null
 # Main program starts here (you shouldn't have to edit this)
 
 function _usage() {
-    echo "usage $0 <base root file> [<json file to add>]"
+    echo "usage $0 <base ROOT file> [<text file to add>]"
 }
 
 function _help() {
@@ -30,15 +30,17 @@ Script to make the creation of b-tagging calibration files less painful
 To use you'll need:
  - A base ROOT file which contains calibrations for the existing
    taggers.
- - Optionally: a json file which you want to add to that file.
+ - Optionally: a text file which you want to add to that file.
 
 This script will:
- - Convert the JSON file to a ROOT file using the included python
-   script. This file will have the same name as the json file, with
+ - Check if the base ROOT file already has a GUID set. If so, it
+   will be removed.
+ - Convert the text file to a ROOT file using the included python
+   script. This file will have the same name as the text file, with
    the extension replaced with '.root'
- - Call 'hadd' to combine the base root file with the new root
+ - Call 'hadd' to combine the base ROOT file with the new ROOT
    file. The resulting file will be called $ROOT_DB_FILE.
- - Set the GUID for this file, and insert the file into the local pool
+ - Set the (new) GUID for this file, and insert the file into the local pool
    file catalogue.
  - Create a local database file and set the appropriate channels.
 
@@ -57,34 +59,34 @@ EOF
 
 DIR=$(dirname $0)
 
-# Arg 1 is the base calibration file, arg 2 is the json file. If the
-# json file is given, we need to build a root file.
+# Arg 1 is the base calibration file, arg 2 is the text file. If the
+# text file is given, we need to build a ROOT file.
 if [[ $# == 2 ]]; then
     if [[ $1 != *.root ]]; then
 	echo "ERROR: first arg should have extension .root" >&2
 	exit 1
     fi
-    if [[ $2 != *.json ]]; then
-	echo "ERROR: second arg should have extension .json" >&2
+    if [[ $2 == *.root ]]; then
+	echo "ERROR: second arg should have a text file extension, e.g. .json" >&2
 	exit 1
     fi
     echo "check for existing GUID in input ROOT calibration file..."
-    NEW_ROOT_FILE=${2%%.json}.root
+    NEW_ROOT_FILE=${2%%.}.root
     python $DIR/removeExistingGUID.py $1 2> $OUT_LOG
-    echo "building root file from json..."
+    echo "building ROOT file from text..."
     python $DIR/addTextFileToRoot.py -v 0 $2 2> $OUT_LOG
     if [[ -f $ROOT_DB_FILE ]]; then
 	echo "$ROOT_DB_FILE already exists, removing..."
 	rm $ROOT_DB_FILE
     fi
 
-    # Hadd the root files together.
+    # Hadd the ROOT files together.
     if ! hadd $ROOT_DB_FILE $NEW_ROOT_FILE $1 &> $OUT_LOG; then
 	echo "error in hadd!" >&2
 	exit 1
     fi
 elif [[ $# == 1 ]]; then
-    # if no json file is given, just copy the base root file
+    # if no text file is given, just copy the base ROOT file
     cp $1 $ROOT_DB_FILE
 else
     _usage
